"""
Configuration file template. 

@author Benjamin Cowen
@date 7 Feb 2022
@contact benjamin.cowen.math@gmail.com
"""

# Experiment settings
dict-name: basic-linear
use-gpu: True

# Dataset
dataset:
  - name: mnist
  - target: input

# Optimizer
optimizer:
  - tag: A
    name: SGD


# Model
model:
  - tag: encoder
    constructor: FISTA
    trainable: False
  - tag: dictionary
    constructor: linear
    optimizer-tag: A
    trainable: True
